ALTER TABLE public.hero_slides ADD COLUMN IF NOT EXISTS highlight text NOT NULL DEFAULT '';

DELETE FROM public.hero_slides;

INSERT INTO public.hero_slides (slug, kicker, title, subtitle, highlight, cta_primary, cta_secondary, cta_link, gradient, icon_name, accent, position, visible)
VALUES
('mega-marketplace','MEGA SOFTWARE MARKETPLACE','12,000+ Software. 80+ Business Categories.','Ready-to-move software solutions for businesses across 80+ industries, all available from one powerful marketplace.','12,000+ Ready Software','Browse Software','Learn More','/demos','from-sky-200 via-cyan-100 to-white','Boxes','text-sky-600',0,true),
('lifetime-249','SIMPLE PRICING','Lifetime Software. Only $249.','One-time payment for a lifetime software license. No complicated subscription model.','$249 Lifetime','View Software','Learn More','/demos','from-violet-200 via-purple-100 to-white','Crown','text-violet-600',1,true),
('no-hidden-charges','TRANSPARENT BUSINESS','No Hidden Charges. Know What You Pay.','Transparent pricing designed to keep your software investment simple, clear and predictable.','NO HIDDEN CHARGES','Explore Pricing','Learn More','/demos','from-emerald-200 via-teal-100 to-white','ShieldCheck','text-emerald-600',2,true),
('no-advance-payment','TRUST-FIRST APPROACH','No Advance Payment. Business Built on Trust.','A trust-focused approach designed to make working with Software Vala simple and transparent.','NO ADVANCE PAYMENT','Talk to Us','Learn More','/demos','from-rose-200 via-pink-100 to-white','BadgeCheck','text-rose-600',3,true),
('support-247','ALWAYS AVAILABLE','24/7 Technical Support. We are Here When You Need Us.','Get ongoing technical assistance and support whenever you need help with your software.','24/7 SUPPORT','Get Support','Learn More','/demos','from-orange-200 via-amber-100 to-white','Clock','text-orange-600',4,true),
('global-opportunity','GLOBAL OPPORTUNITY','Buy • Sell • Resell • Franchise • Grow','Turn software into a business opportunity with global reseller, distributor and franchise partnership options.','GLOBAL BUSINESS OPPORTUNITY','Become a Partner','Learn More','/demos','from-lime-200 via-green-100 to-white','Globe2','text-green-600',5,true),
('partnership-programs','PARTNERSHIP PROGRAMS','Build Your Business With Software Vala.','Choose the partnership model that fits your business: Reseller, Distributor, Franchise or Influencer.','RESELLER • DISTRIBUTOR • FRANCHISE • INFLUENCER','Join Partnership','Learn More','/demos','from-indigo-200 via-sky-100 to-white','Users','text-indigo-600',6,true),
('demos-tutorials','SELL WITH CONFIDENCE','Demo Videos & Tutorials. Show. Explain. Sell.','Product demos and tutorial resources make it easier to understand software and present solutions to your customers.','DEMO + TUTORIAL SUPPORT','Watch Demos','Learn More','/demos','from-yellow-200 via-amber-100 to-white','Play','text-amber-600',7,true),
('skip-scratch','SMARTER WAY TO BUILD','Do not Build Software From Scratch. Build Your Business With Software Vala.','Avoid years of development, large technical teams and massive infrastructure costs. Start with ready-made software solutions.','SAVE DEVELOPMENT COST & TIME','Start Your Business','Learn More','/demos','from-cyan-200 via-sky-100 to-white','Rocket','text-cyan-600',8,true),
('name-of-trust','SOFTWARE VALA','The Name of Trust.','A complete software marketplace connecting ready-made solutions, businesses, customers and partnership opportunities on one platform.','12,000+ Software • 80+ Categories • $249 Lifetime • 24/7 Support','Explore Software Vala','Become a Partner','/demos','from-blue-200 via-white to-amber-100','Sparkles','text-blue-600',9,true);